import { Campaign } from './types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    title: 'Gear Up & Get Rewarded',
    badge: 'NEW CONTRACT',
    description: 'Ends Dec 31, 2025 • Target: 85% Reach',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    startDate: '1 Juli 2025',
    endDate: '31 December 2025',
    progress: 50,
    status: 'active',
    fullDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
    partsIncluded: ['Parts Number A', 'Parts Number B', 'Parts Number C'],
    termsAndConditions: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rewards: ['Reward A', 'Reward B'],
  },
  {
    id: '2',
    title: 'Campaign Name',
    badge: 'ACTIVE',
    description: 'Periode: Jan - Mar 2025',
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800',
    startDate: '1 Januari 2025',
    endDate: '31 Maret 2025',
    progress: 75,
    status: 'active',
    fullDescription: 'Campaign description for special promotion period. Join now and get exclusive rewards.',
    partsIncluded: ['Parts Number X', 'Parts Number Y'],
    termsAndConditions: 'Terms and conditions apply. Please read carefully before joining the campaign.',
    rewards: ['Special Discount', 'Bonus Points'],
  },
  {
    id: '3',
    title: 'Summer Promo 2025',
    badge: 'UPCOMING',
    description: 'Starting April 2025',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    startDate: '1 April 2025',
    endDate: '30 Juni 2025',
    progress: 0,
    status: 'upcoming',
    fullDescription: 'Get ready for our biggest summer promotion. More details coming soon.',
    partsIncluded: ['All Parts Category'],
    termsAndConditions: 'Full terms will be announced soon.',
    rewards: ['Mystery Rewards'],
  },
];
